version: 2.1
jobs:
  build-and-push-ecr:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Authenticate with ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      # ... (other steps remain unchanged)
workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push-ecr