version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t hello-world-express .

  runner-test:
    machine: true
    resource_class: virus/windows
    steps:
      - run: echo "Hi I'm on Runners!"

  push-to-ecr:
    docker:
      - image: amazon/aws-cli
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Authenticate with ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION \
              | docker login --username AWS --password-stdin $ECR_REGISTRY
      - run:
          name: Build, Tag, and Push Docker Image to ECR
          command: |
            docker build -t $ECR_REPOSITORY .
            docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

workflows:
  version: 2

  testing:
    jobs:
      - build
      - runner-test

  ecr-deploy:
    jobs:
      - build
      - push-to-ecr:
          requires:
            - build
