version: 2.1
jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Authenticate with ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      # ... (other steps remain unchanged)
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-push