version: 2.1
jobs:
  check-k8s-manifests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Check Kubernetes manifests exist
          command: |
            if [ ! -f kubernetes/deployment.yaml ]; then
              echo "Error: kubernetes/deployment.yaml not found"
              exit 1
            fi
            if [ ! -f kubernetes/service.yaml ]; then
              echo "Error: kubernetes/service.yaml not found"
              exit 1
            fi
workflows:
  version: 2
  k8s-deploy:
    jobs:
      - check-k8s-manifests