version: 2.1

executors:
  linux-self-hosted:
    machine:
      enabled: true
    resource_class: virus/windows

jobs:
  build:
    executor: linux-self-hosted
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t hello-world-express .

  push-to-ecr:
    executor: linux-self-hosted
    steps:
      - checkout
      - run:
          name: Check AWS CLI and Docker Versions
          command: |
            aws --version
            docker --version
      - run:
          name: Authenticate with ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | \
              docker login --username AWS --password-stdin $ECR_REGISTRY
      - run:
          name: Build, Tag, and Push Docker Image to ECR
          command: |
            IMAGE_TAG="v1.0.${CIRCLE_BUILD_NUM}"
            echo "Using image tag: $IMAGE_TAG"

            docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
            docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            # Also tag as 'latest' to maintain current behavior
            docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest

            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

workflows:
  version: 2

  ecr-deploy:
    jobs:
      - build
      - push-to-ecr:
          requires:
            - build