version: 2.1

executors:
  self-hosted-windows:
    machine:
      enabled: true
    resource_class: virus/windows

jobs:
  build:
    executor: self-hosted-windows
    steps:
      - checkout
      - run:
          name: Build Docker Image
          shell: powershell.exe
          command: |
            docker build -t hello-world-express .

  runner-test:
    executor: self-hosted-windows
    steps:
      - run:
          name: Hello from Runner
          shell: powershell.exe
          command: echo "Hi I'm on Runners!"

  push-to-ecr:
    executor: self-hosted-windows
    steps:
      - checkout
      - run:
          name: Authenticate with ECR
          shell: powershell.exe
          command: |
            aws ecr get-login-password --region $Env:AWS_REGION | docker login --username AWS --password-stdin $Env:ECR_REGISTRY
      - run:
          name: Build, Tag, and Push Docker Image to ECR
          shell: powershell.exe
          command: |
            docker build -t $Env:ECR_REPOSITORY .
            docker tag $Env:ECR_REPOSITORY:latest $Env:ECR_REGISTRY/$Env:ECR_REPOSITORY:latest
            docker push $Env:ECR_REGISTRY/$Env:ECR_REPOSITORY:latest

workflows:
  version: 2

  testing:
    jobs:
      - build
      - runner-test

  ecr-deploy:
    jobs:
      - build
      - push-to-ecr:
          requires:
            - build
