version: 2.1

executors:
  linux-runner:
    machine:
      enabled: true
    resource_class: virus/windows  # your self-hosted runner label

jobs:
  build:
    executor: linux-runner
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t hello-world-express .

  runner-test:
    executor: linux-runner
    steps:
      - run:
          name: Say Hi from Self-hosted Runner
          command: echo "Hi I'm on the self-hosted runner!"

  push-to-ecr:
    executor: linux-runner
    steps:
      - checkout
      - run:
          name: Authenticate with ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - run:
          name: Build, Tag, and Push Docker Image to ECR
          command: |
            docker build -t $ECR_REPOSITORY .
            docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

workflows:
  version: 2

  testing:
    jobs:
      - build
      - runner-test

  ecr-deploy:
    jobs:
      - build
      - push-to-ecr:
          requires:
            - build
