apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-express
  template:
    metadata:
      labels:
        app: hello-world-express
    spec:
      containers:
      - name: hello-world-express
        image: 244706281787.dkr.ecr.ap-south-1.amazonaws.com/circleci:v1.0.${CIRCLE_BUILD_NUM}
        ports:
        - containerPort: 3000
