apiVersion: v1
kind: Service
metadata:
  name: hello-world-express
spec:
  selector:
    app: hello-world-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
